run:
  go: 1.18

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 5
  gomnd:
    settings:
      mnd:
        # don't include the "operation" and "assign"
        checks: argument,case,condition,return
  govet:
    check-shadowing: true
  lll:
    line-length: 140
  maligned:
    suggest-new: true
  misspell:
    locale: US

# Reference : https://golangci-lint.run/usage/linters/
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    # Recommend using the following linters at a minimum
    # Minimum Linters help to catch the most common issues 
    # Balance high bar for code quality without being unnecessarily prescriptive
    - deadcode	# to point out unused code
    - errcheck # to ensure that errors are handled
    - gosimple # to simplify code
    - goimports # to format code and manage imports
    - govet # to analyze code for common mistakes
    - gosec # to point out security problems 
    - ineffassign # to point out assignments to existing variables that are not used
    - revive # to point out common style mistakes
    - staticcheck # to do various static analysis checks
    - typecheck # parses and type-checks Go code
    - unused # to point out unused constants, variables, functions and types
    - varcheck # to point out unused global variables and constants

    # Additional Linters
    - asciicheck
    - dogsled
    - dupl
    - decorder 
    - depguard 
    - exportloopref
    - exhaustive
    # - errchkjson
    - errname
    - errorlint 
    - exhaustive 
    # - exhaustruct 
    - funlen
    - containedctx
    - gochecknoglobals
    - gochecknoinits
    - gocognit 
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox 
    - gofmt
    - gomnd
    - goprintffuncname
    - maintidx
    - misspell
    - nakedret
    - unconvert

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude:
  - 'Error return value of `json.Unmarshal` is not checked'
  - 'Error return value of `awsWrapper.cache.Set` is not checked'
  - 'Error return value of `httpServer.Shutdown` is not checked'
  - 'Error return value of `responseWritter.Write` is not checked'


